name: Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    name: Test Build on ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            display_name: Windows
          - os: ubuntu-24.04
            display_name: Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Test build process
      run: python build.py
      timeout-minutes: 15
      env:
        PYTHONIOENCODING: utf-8

    - name: Test executable
      run: |
        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          ./dist/Sniper-IT-Agent.exe --help && echo "Windows executable test passed"
        else
          ./dist/Sniper-IT-Agent --help && echo "Linux executable test passed"
        fi
      shell: bash

    - name: Test data collection (no API)
      run: |
        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          echo "Testing Windows data collection would require API setup"
        else
          echo "Testing Linux data collection would require API setup"
        fi
      shell: bash